language: cpp

compiler:
  - clang
  - gcc

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

script:
  - $CC -c spotc.c -I. -O2 && $CXX -o converter samples/converter.cc spot.cpp spotc.o -I. -Isamples -std=c++11 -lX11 -lrt -pthread -O2 
  - $CC -c spotc.c -I. -O2 && $CXX -o readme    samples/readme.cc    spot.cpp spotc.o -I. -Isamples -std=c++11 -lX11 -lrt -pthread -O2 
  - $CC -c spotc.c -I. -O2 && $CXX -o viewer    samples/viewer.cc    spot.cpp spotc.o -I. -Isamples -std=c++11 -lX11 -lrt -pthread -O2 
  - $CC -c spotc.c -I. -O2 && $CXX -o filt      samples/filt.cc      spot.cpp spotc.o -I. -Isamples -std=c++11 -lX11 -lrt -pthread -O2 
  - $CC -c spotc.c -I. -O2 && $CXX -o transfer  samples/transfer.cc  spot.cpp spotc.o -I. -Isamples -std=c++11 -lX11 -lrt -pthread -O2 
