language: cpp
sudo: required

compiler:
  - clang
  - gcc

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

script:
  - $CXX sample.cc -I. -std=c++11 -lrt -O2 -o sample && ./sample
  - $CXX tests.cxx -I. -std=c++11 -lrt -O2 -o tests && ./tests
